/*
================================================================
  Hero Profile Card — celebrate.js
  Coleg Llandrillo · Academi Ddigidol 2025

  Students do NOT edit this file.

  1. STAT BARS
     Reads data-points (0-4) on each .bar-fill and sets
     the bar width automatically on page load.
     4 points = 100%, 3 = 75%, 2 = 50%, 1 = 25%, 0 = 0%

  2. CELEBRATION
     The function activatePower() is called by the student's
     button via onclick="activatePower()"
     No class or ID needed on the button.
================================================================
*/

/* ── SET STAT BARS ON PAGE LOAD ─────────────────────────────── */

window.addEventListener('load', function () {
  setStatBars();
});

function setStatBars() {
  var bars = document.querySelectorAll('.bar-fill');
  for (var i = 0; i < bars.length; i++) {
    var pts = parseInt(bars[i].getAttribute('data-points'), 10) || 0;
    if (pts > 4) {
      pts = 4;
    }
    if (pts < 0) {
      pts = 0;
    }
    bars[i].style.width = (pts / 4) * 100 + '%';
  }
}

/* ── ACTIVATE POWER — called by student's button onclick ─────── */

function activatePower() {
  var btn = document.querySelector('button');
  if (btn) {
    btn.disabled = true;
    btn.textContent = 'Pwerau Actif / Powers Active';
  }
  fireParticles();
  showMessage();
}

/* ── GET THEME COLOURS ──────────────────────────────────────── */

function getTheme() {
  var cl = document.body.classList;
  if (cl.contains('theme-arcane')) {
    return {
      welsh: "Hud Wedi'i Ryddhau!",
      english: 'Magic Unleashed!',
      colours: ['#40d8c0', '#8060d0', '#a060d0', '#60e8d0', '#ffffff'],
      strip: '#40d8c0',
    };
  }
  if (cl.contains('theme-valor')) {
    return {
      welsh: "Anrhydedd Wedi'i Ennill!",
      english: 'Honour Earned!',
      colours: ['#7070e0', '#8050c0', '#e8a040', '#9090f8', '#ffffff'],
      strip: '#7070e0',
    };
  }
  if (cl.contains('theme-dragon')) {
    return {
      welsh: "Grym Wedi'i Actifadu!",
      english: 'Power Activated!',
      colours: ['#e04040', '#c03030', '#e8a040', '#f06060', '#ffffff'],
      strip: '#e04040',
    };
  }
  if (cl.contains('theme-shadow')) {
    return {
      welsh: "Cysgod Wedi'i Ryddhau!",
      english: 'Shadow Released!',
      colours: ['#50c060', '#78c030', '#40b050', '#60d070', '#ffffff'],
      strip: '#50c060',
    };
  }
  return {
    welsh: "Gallu Wedi'i Actifadu!",
    english: 'Power Unlocked!',
    colours: ['#aaaaaa', '#cccccc', '#eeeeee', '#888888', '#ffffff'],
    strip: '#aaaaaa',
  };
}

/* ── PARTICLES ──────────────────────────────────────────────── */

function fireParticles() {
  var t = getTheme();
  for (var i = 0; i < 100; i++) {
    (function (delay) {
      setTimeout(function () {
        createParticle(t.colours[Math.floor(Math.random() * t.colours.length)]);
      }, delay);
    })(i * 28);
  }
}

function createParticle(colour) {
  var p = document.createElement('div');
  var size = Math.random() * 9 + 4;
  var startX = Math.random() * window.innerWidth;
  var vx = (Math.random() - 0.5) * 420;
  var vy = -(Math.random() * 500 + 160);

  p.style.cssText = [
    'position:fixed',
    'width:' + size + 'px',
    'height:' + size + 'px',
    'background:' + colour,
    'border-radius:' + (Math.random() > 0.5 ? '50%' : '3px'),
    'left:' + startX + 'px',
    'top:' + window.innerHeight + 'px',
    'pointer-events:none',
    'z-index:9999',
  ].join(';');

  document.body.appendChild(p);

  var posX = startX;
  var posY = window.innerHeight;
  var opacity = 1;

  var timer = setInterval(function () {
    vy += 14;
    posX += vx / 60;
    posY += vy / 60;
    opacity -= 0.013;
    p.style.left = posX + 'px';
    p.style.top = posY + 'px';
    p.style.opacity = opacity;
    if (opacity <= 0 || posY > window.innerHeight + 20) {
      clearInterval(timer);
      if (p.parentNode) {
        p.parentNode.removeChild(p);
      }
    }
  }, 16);
}

/* ── MESSAGE OVERLAY ────────────────────────────────────────── */

function showMessage() {
  var t = getTheme();

  var overlay = document.createElement('div');
  overlay.style.cssText = [
    'position:fixed',
    'inset:0',
    'display:flex',
    'align-items:center',
    'justify-content:center',
    'z-index:10000',
    'pointer-events:none',
    'backdrop-filter:blur(6px)',
    '-webkit-backdrop-filter:blur(6px)',
  ].join(';');

  var panel = document.createElement('div');
  panel.style.cssText = [
    'background:rgba(0,0,0,0.55)',
    'border:1px solid rgba(255,255,255,0.2)',
    'border-top:1px solid rgba(255,255,255,0.35)',
    'border-left:4px solid ' + t.strip,
    'border-radius:16px',
    'padding:44px 56px',
    'text-align:center',
    'font-family:Arial,sans-serif',
    'box-shadow:0 16px 48px rgba(0,0,0,0.6)',
    'animation:popIn 0.4s cubic-bezier(0.175,0.885,0.32,1.275)',
    'max-width:500px',
  ].join(';');

  panel.innerHTML =
    '<p style="font-size:40px;margin-bottom:16px;">⚔️</p>' +
    '<p style="font-size:24px;font-weight:700;letter-spacing:1px;color:#ffffff;margin-bottom:8px;">' +
    t.welsh +
    '</p>' +
    '<p style="font-size:15px;font-weight:400;letter-spacing:0;text-transform:none;color:rgba(255,255,255,0.7);margin-bottom:24px;">' +
    t.english +
    '</p>' +
    '<p style="font-size:11px;font-weight:700;letter-spacing:2px;color:#4ade80;margin-bottom:4px;">CROESO I GOLEG LLANDRILLO</p>' +
    '<p style="font-size:11px;font-weight:400;letter-spacing:2px;text-transform:none;color:rgba(74,222,128,0.6);">WELCOME TO COLEG LLANDRILLO</p>';

  var sty = document.createElement('style');
  sty.textContent =
    '@keyframes popIn{from{transform:scale(0.3);opacity:0;}to{transform:scale(1);opacity:1;}}';
  document.head.appendChild(sty);
  overlay.appendChild(panel);
  document.body.appendChild(overlay);

  setTimeout(function () {
    overlay.style.transition = 'opacity 1.2s ease';
    overlay.style.opacity = '0';
    setTimeout(function () {
      if (overlay.parentNode) {
        overlay.parentNode.removeChild(overlay);
      }
    }, 1200);
  }, 4500);
}
